Models/ErrorViewModel.cs
namespace LaMiaPizzeria.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Ingrediente.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LaMiaPizzeria.Models
{
    public class Ingrediente
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public List<Pizza> PizzaList { get; set; }

        public Ingrediente(string name)
        {
            Name = name;            
        }

    }
}

Models/Pizza.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LaMiaPizzeria.Models
{
    public class Pizza
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string PhotoUrl { get; set; }
        public double Price { get; set; }
        public List<Ingrediente> IngredienteList { get; set; }

        public Pizza(string name, string description, string photoUrl, double price)
        {
            Name = name;
            Description = description;
            PhotoUrl = photoUrl;
            Price = price;
        }


        public void SetIngredienti(Ingrediente ingrediente1, Ingrediente ingrediente2, Ingrediente ingrediente3)
        {
            IngredienteList.Add(ingrediente1);
            IngredienteList.Add(ingrediente2);
            IngredienteList.Add(ingrediente3);
        }

        public void SetIngredienti(Ingrediente ingrediente1, Ingrediente ingrediente2)
        {
            IngredienteList.Add(ingrediente1);
            IngredienteList.Add(ingrediente2);
        }

        public void SetIngredienti(Ingrediente ingrediente1)
        {
            IngredienteList.Add(ingrediente1);
        }

    }
}

Controllers/HomeController.cs
using LaMiaPizzeria.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace LaMiaPizzeria.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PizzaController.cs
using LaMiaPizzeria.Data;
using LaMiaPizzeria.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace LaMiaPizzeria.Controllers
{
    public class PizzaController : Controller
    {
        public IActionResult Index()
        {
            using (PizzaContext db = new PizzaContext())
            {
                List<Pizza> pizzaList = db.PizzaList.OrderBy(pizza => pizza.Id).ToList<Pizza>();
                if(pizzaList == null)
                {
                    return NotFound("Pizze non presenti");
                }
                return View(pizzaList);
            }

        }

        public IActionResult Details(int id)
        {
            using (PizzaContext db = new PizzaContext())
            {  
                Pizza pizza  = db.PizzaList.Where(pizza => pizza.Id == id).FirstOrDefault();

                if(pizza == null)
                {
                    return NotFound("Pizza non trovata");
                }
                else
                {
                    db.Entry(pizza).Collection("IngredienteList").Load();
                    return View("Details", pizza);
                }
               
            }

        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <h2  class="text-dark">Visualizza le nostre pizze!!</h2>    
    <p>  <a class="btn btn-primary" href="~/Pizza">QUI</a></p>
</div>

Views/Pizza/Details.cshtml
@model Pizza
@{
    
}


<div class="container text-dark">
    <h2>@Model.Name</h2>
    <div class="row">
        <div class="w-50">
            <img class="w-100" src="@Model.PhotoUrl"/>
        </div>
        <div class="w-50">
            <h3>Descrizione</h3>
            <p>@Model.Description</p>
            <h3>Prezzo</h3>
            <span>@Model.Price &euro;</span>
            
            <h3>Ingredienti</h3>
            @if(Model.IngredienteList.Count() > 0)
            {
                foreach(Ingrediente ing in Model.IngredienteList)
                {                
                    <span> @ing.Name</span>
                }
            }
            else
            {
                <span>-</span>
            }
    </div>
    <a  class="btn btn-danger mt-2 " href="@Url.Action("Index","Pizza")">Indietro</a>
</div>

Views/Pizza/Index.cshtml
@{
    ViewData["Title"] = "Lista Pizze";
}

@model List<Pizza>

<div>
    <table  class="table table-hover">
        <tr>
            <th class="col-2">Immagine</th>
            <th class="col-2">Nome</th>
            <th class="col-2">Desscrizione</th>
            <th class="col-2">Prezzo</th>
            <th class="col-2">Ingredienti</th>
        </tr>

        @foreach(Pizza pizza in Model)
        {
            <tr class="my-lg-2 ">
                <td><img src="@pizza.PhotoUrl" class="w-50"/></td>
                <td class="align-middle">@pizza.Name</td>
                <td class="align-middle">@pizza.Description</td>
                <td class="align-middle">@pizza.Price euro</td>
                <td class="align-middle"><a class="btn btn-success" href="@Url.Action("Details","Pizza",new { id = @pizza.Id})">Visualizza</a></td>
             </tr>
        }
    </table>
</div>

Views/Shared/_Footer.cshtml
@{
    List<string> info = new List<string> { "contatti", "dove trovarci", "info_allergeni", "provenienza dei nostri prodotti" };
    
}
    <footer class="border-top pt-3">
        <h6 class="text-center pb-3">Di seguito i link per togliervi ogni dubbio sulla qualità dei nostri prodotti! Occhio agli allergenii!!</h6>
        <ul class="row col-12 list-unstyled text-center">
            @foreach(string i in info)
            {
                <li class="col-3"><a href="">@i</a></li>        
            }
        </ul>
        <div class="text-center">Made with &hearts;</div>
    </footer>

Views/Shared/_Header.cshtml
<header >
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-warning border-bottom box-shadow mb-3 ">
            <div class="container-fluid ">   
                <a class="navbar-brand text-danger" asp-controller="Home" asp-action="Index">Da Gianfri u Pizzajuol</a>                
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav mr-auto flex-grow-1 ">                        
                        <li class="nav-item"><a class="dropdown-item" href="/">Home</a></li>
                        <li class="nav-item"><a class="dropdown-item" href="/Pizza">Le nostre pizze</a></li>  
                        <li class="nav-item"> <a class="dropdown-item" href="/Ricarica">Contatti</a></li>  
                        <li class="nav-item"><a class="dropdown-item" href="/Supporto">Effettua un ordine</a></li>  
                        <li class="nav-item"><a class="dropdown-item" href="#">Info allergeni</a></li>  
                        <li class="nav-item"><a class="dropdown-item" href="/Supporto">Provenienza dei nostri prodotti</a></li>  
                    </ul>
                </div>                
            </div>
        </nav>
</header>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LaMiaPizzeria</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LaMiaPizzeria.styles.css" asp-append-version="true" />
</head>
<body>
    
   @Html.Partial("_Header")
    <div class="container">
        <main role="main" class="pb-3 ggf-nav"">
            @RenderBody()
        </main>
    </div>
    @Html.Partial("_Footer")


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>